### ISSUE TITLE
When deploying the Confidential VM, it throws an error "error while executing confidential virtual machine template deployment" - line 78 and 130

### ISSUE THREAD

**Issue by dpaardenkooper** [Azure/cloud-for-sovereignty-quickstarts#11]
Hi Team,

I'm deploying the vm as described on github, filling the parameters as described.

Error message: 
Error while executing confidential virtual machine template deployment
confidentialVirtualMachineAccelerator.ps1: line 78 at <scriptBlock>
confidentialVirtualMachineAccelerator.ps1: line 130 at <scriptBlock> <no file>: line 1

Script used:
confidentialVirtualMachineAccelerator.ps1

It looks like an extra requirement is needed:
Virtual machine Properties/userData block. Carries a string that the VM can access thorugh the IMDS service, see https://learn.microsoft.com/en-us/azure/virtual-machines/user-data.').

Please confirm.

Kind regards,
Dinant

**Comment by azure-lm** [comment]
Hello, I'm looking into this and not able to replicate the issue. The user-data property should be sent across, but it has no data in this example.

Can you look at the deployment history and see which resource being deployed is failing and send that error message? Should be easiest to find in the portal in the resource group where the deployment is happening under the "Deployments" blade.
