### ISSUE TITLE
Cannot connect to HR App portal - connection refused

### ISSUE THREAD

**Issue by PaulSlijkhuis** [Azure/cloud-for-sovereignty-quickstarts#15]
After deployment of the quickstart, the HP app portal does not accept any connections. Connecting via https://<ip>:5001. 
Error message in browser: err_connection_refused

Previously, the website was working just fine. No error messages in deployment have showed. Tried multiple browsers, without Defender fw, reboot of linux VM, DNS flush, re-deployment, multiple stepping stone VMs. 

Please help to troubleshoot / fix this issue. 

As a MC4Sov partner, I want to be able to show the capabilities of sovereign controls.

**Comment by KevinRabun** [comment]
Thank you for opening an issue. Are you attempting to connect via localhost or the VM IP adress?

**Comment by PaulSlijkhuis** [comment]
The VM hosting the web app is actually the hardended Linux VM fromt he quickstart deployment. My attempt is to browse via a remote Windows VM by accessing the ip address on port 5001. Tried to run the VM is in the same subnet, or via peered subnet, both have same outcome.

**Comment by azure-lm** [comment]
On the HR VM, can you run the following and let us know what responses you get. The first command should print any startup errors if they exist. The second command should return an HTML page if the site is up and running.

```
journalctl -u ContosoHR.service
curl -k https://localhost:5001
```

You can use the **Run command** options via the portal to do this: https://learn.microsoft.com/en-us/azure/virtual-machines/windows/run-command

**Comment by PaulSlijkhuis** [comment]
Hi,

The error seems consistent with the reported error.

Journalctl >> Couldn't find a project to run. Ensure a project exists in /home/contosohr/>
curl >> (7) Failed to connect to localhost port 5001 after 0 ms: Connection refused

[cid:9b364e90-87cb-4018-90bd-55694bca1077]

Regards, Paul
________________________________

**Comment by azure-lm** [comment]
This is odd, if it was previously working then I would expect the journal cmd would have found relevant logs. Note that the deployment script is not intended to be ran multiple times. It shouldn't break things with a rerun, but perhaps there's an issue there.

For the most, if there's an issue with the HR app the best way to resolve is to drop the relevant Azure resources and redeploy. Have you tried that by chance, or do you have any issues with attempting that? The only time I've seen the app completely fail is related to DB problems, so would be good to double check there's no errors with the DB initialization process.

**Comment by PaulSlijkhuis** [comment]
The approach I am following is to destroy and redeploy the solution over and over, while keeping the admin / non-confidential resources in place. I update the RG numbering in order to bypass the redeployment error of the Keyvault with soft delete protection. Such a redeployment takes 15 minutes which is fine to do. But currently also not the solution because I keep getting the same result.

Unfortunately, I cannot determine other database errors. Access to the database via SQL data studio works fine.

Do have any specific places to check or logging I should review?

Thank you.
________________________________

**Comment by azure-lm** [comment]
Hi Paul, we have pushed out a new hotfix (v1.1.1) that should address these issues. Can you please check if these errors persist with that version?

**Comment by PaulSlijkhuis** [comment]
yes! I can confirm this is a good version. The web app is running again after deployment.

Thank you,
Paul  
________________________________
